In [1]:
from pytrends.request import TrendReq
from pprint import pprint
import pytrends
import pandas as pd
import time
import datetime
from datetime import datetime, date, time

In [4]:
pytrend = TrendReq(hl='en-US', tz=360)
keywords = ['五峰旗瀑布']
pytrend.build_payload(kw_list=keywords,cat=0,timeframe='2020-1-1 2020-12-31',geo='TW',gprop='')

In [5]:
pytrend.interest_over_time()

            五峰旗瀑布  isPartial
date
2020-01-05     27      False
2020-01-12     27      False
2020-01-19     50      False
2020-01-26     22      False
2020-02-02     24      False
2020-02-09     43      False
2020-02-16     40      False
2020-02-23     36      False
2020-03-01     23      False
2020-03-08     16      False
2020-03-15     16      False
2020-03-22     32      False
2020-03-29     49      False
2020-04-05     19      False
2020-04-12     48      False
2020-04-19     32      False
2020-04-26     63      False
2020-05-03     75      False
2020-05-10     35      False
2020-05-17     22      False
2020-05-24     32      False
2020-05-31     43      False
2020-06-07     64      False
2020-06-14     53      False
2020-06-21     76      False
2020-06-28     54      False
2020-07-05     49      False
2020-07-12    100      False
2020-07-19     70      False
2020-07-26     60      False
2020-08-02     74      False
2020-08-09     68      False
2020-08-16     66      False
2020-08-23     33      False
2020-08-30     50      False
2020-09-06     56      False
2020-09-13     59      False
2020-09-20     30      False
2020-09-27     58      False
2020-10-04     53      False
2020-10-11     46      False
2020-10-18     29      False
2020-10-25     35      False
2020-11-01     35      False
2020-11-08     53      False
2020-11-15     35      False
2020-11-22     43      False
2020-11-29     22      False
2020-12-06     15      False
2020-12-13     26      False
2020-12-20      4      False
2020-12-27     26      False

In [2]:
keywords = ['五峰旗瀑布']

In [3]:
df = pd.DataFrame()
for i in range(1,6):
    print(i)
    if i== 1 or i==3 or i==5:
        gotr_1 = pytrend.get_historical_interest(keywords, year_start=2021, month_start=i, day_start=1, hour_start=0, year_end=2021, month_end=i, day_end=31, hour_end=23, cat=3, sleep=0)
        df = pd.concat([df,gotr_1])
    elif i==4 :
        gotr_2 = pytrend.get_historical_interest(keywords, year_start=2021, month_start=i, day_start=1, hour_start=0, year_end=2021, month_end=i, day_end=30, hour_end=23, cat=0, sleep=0)
        df = pd.concat([df,gotr_2])
    else:
        gotr_3 = pytrend.get_historical_interest(keywords, year_start=2021, month_start=i, day_start=1, hour_start=0, year_end=2021, month_end=i, day_end=28, hour_end=23, cat=0, sleep=0)
        df = pd.concat([df,gotr_3])

1

NameError: name 'pytrend' is not defined

In [22]:
df

                     五峰旗瀑布  isPartial
date
2021-01-01 00:00:00      0      False
2021-01-01 01:00:00      0      False
2021-01-01 02:00:00      0      False
2021-01-01 03:00:00      0      False
2021-01-01 04:00:00     97      False
...                    ...        ...
2021-05-28 20:00:00      0      False
2021-05-28 21:00:00      0      False
2021-05-28 22:00:00      0      False
2021-05-28 23:00:00      0      False
2021-05-29 00:00:00      0      False

[3402 rows x 2 columns]

In [23]:
df.to_csv('/Users/julia/Desktop/科技部大專生計畫/GoogleTrend爬蟲/2021gt_五峰旗.csv')

In [4]:
df.to_csv('/Users/julia/Desktop/科技部大專生計畫/GoogleTrend爬蟲/2021_gt_冬山河親水公園.csv')

In [6]:
df

Empty DataFrame
Columns: []
Index: []

In [25]:
lst = [['清水地熱','三星'],['龍潭湖','大礁溪'],['五峰旗','礁溪'],['冬山河親水公園','五結'],['傳統藝術中心','五結']]
pd.DataFrame(lst,columns=[['主要景點','天氣測站']])

      主要景點 天氣測站
0     清水地熱   三星
1      龍潭湖  大礁溪
2      五峰旗   礁溪
3  冬山河親水公園   五結
4   傳統藝術中心   五結